### ISSUE TITLE
Incomplete initialization of 't'

### ISSUE THREAD

**Issue by abduranjum** [jeduan/corona-mixpanel#1]
I got the following error:
offlinequeue.lua:32: attempt to index local 't' (a nil value)

function M.newQueue(onResultOrParams)
    if M.inited then
        return M
    end

--->    local t 
...

I updated it to
-->    local t =  {}

Now it works fine, without any error.

**Comment by jeduan** [comment]
Thank you for your reports @abduranjum 

Apartently it has to do with bower dependencies. I uploaded a Release in the releases section that should work correctly.
