### ISSUE TITLE
Missing file 'inspect'

### ISSUE THREAD

**Issue by abduranjum** [jeduan/corona-mixpanel#2]
In log.lua, the first line is as following:
local inspect = require 'vendor.inspect.inspect'
But I could not find this file. As log.lua was only logging things, I simply commented the initialization and uses of 'inspect', which solved the issue.

**Comment by jeduan** [comment]
The log you found is a bit newer. It uses https://github.com/kikito/inspect.lua which is the inspect you are missing. Sorry for the documentation shortcoming.

**Comment by abduranjum** [comment]
Thanks!
